# Generated by Django 4.1.6 on 2023-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=100)),
                ('Artist', models.CharField(max_length=100)),
            ],
        ),
    ]
