# Generated by Django 4.1.6 on 2023-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='song',
            field=models.FileField(default=2, upload_to='song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
